version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_unioeste
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090" # Porta da interface de consultas do Prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway" # Permite ao container falar com o host Linux

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_unioeste
    restart: unless-stopped
    ports:
      - "3000:3000" # Porta de acesso aos painéis visuais
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Senha padrão para seu login inicial
    volumes:
      - grafana_storage:/var/lib/grafana

volumes:
  grafana_storage: